// Mocks generated by Mockito 5.3.0 from annotations
// in dataverse_accounts_sample_app/test/src/repositories/account_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dataverse_accounts_sample_app/src/data_providers/accounts/account_api_provider.dart'
    as _i4;
import 'package:dataverse_accounts_sample_app/src/models/account_model.dart'
    as _i6;
import 'package:dataverse_accounts_sample_app/src/network/aad_oauth_client.dart'
    as _i3;
import 'package:dataverse_accounts_sample_app/src/network/api_client.dart'
    as _i2;
import 'package:dataverse_accounts_sample_app/src/utils/shared_preferences_storage.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeAadOauthClient_1 extends _i1.SmartFake
    implements _i3.AadOauthClient {
  _FakeAadOauthClient_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [AccountApiProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAccountApiProvider extends _i1.Mock
    implements _i4.AccountApiProvider {
  MockAccountApiProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get apiClient => (super.noSuchMethod(
          Invocation.getter(#apiClient),
          returnValue: _FakeApiClient_0(this, Invocation.getter(#apiClient)))
      as _i2.ApiClient);
  @override
  _i3.AadOauthClient get aadOauthClient => (super.noSuchMethod(
          Invocation.getter(#aadOauthClient),
          returnValue:
              _FakeAadOauthClient_1(this, Invocation.getter(#aadOauthClient)))
      as _i3.AadOauthClient);
  @override
  _i5.Future<_i6.AccountModel>? fetchAccountListWithSearch(
          String? searchWord) =>
      (super.noSuchMethod(
              Invocation.method(#fetchAccountListWithSearch, [searchWord]))
          as _i5.Future<_i6.AccountModel>?);
}

/// A class which mocks [SharedPreferencesStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedPreferencesStorage extends _i1.Mock
    implements _i7.SharedPreferencesStorage {
  MockSharedPreferencesStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> setAuthToken(String? token) => (super.noSuchMethod(
      Invocation.method(#setAuthToken, [token]),
      returnValue: _i5.Future<void>.value(),
      returnValueForMissingStub: _i5.Future<void>.value()) as _i5.Future<void>);
}
